### ISSUE TITLE
dependencies are bundled unnecessarily when using umd

### ISSUE THREAD

**Issue by darrenjennings** [Kong/kongponents#165]
- KToaster bundles KAlert
- KAlert bundles KIcon
- KModal bunldes KButton
- KEmptyState bundles KButton
- KSlideout bundles KCard, KIcon

Investigate if these should be peerDependencies. For instance, KToaster has a dep of KAlert, but does not compile KAlert correctly and still requires a loader for KIcon. If we move this to peerDep then users could use bundled KIcon which takes care of raw-loader.

**Comment by xitongzou** [comment]
Created ticket here: https://konghq.atlassian.net/browse/INTF-2492
