### ISSUE TITLE
KInputSwitch: change event emitted twice when clicking

### ISSUE THREAD

**Issue by johncowen** [Kong/kongponents#1929]
Seems to be that the underlying `input` fires an event for `change` and `input`, meaning `KInputSwitch@change` gets emitted twice. 

https://github.com/Kong/kongponents/blob/00c25c83e37c13035837898f58162b8e22c23f6b/src/components/KInputSwitch/KInputSwitch.vue#L48-L49

Not sure why the `input` listener/handler is required?

**Comment by portikM** [comment]
This was fixed in https://github.com/Kong/kongponents/pull/1956/files
