### ISSUE TITLE
KIcon does not support elements other than <path />

### ISSUE THREAD

**Issue by travispamaral** [Kong/kongponents#230]
Should support rect, circle, etc if possible.

**Comment by travispamaral** [comment]
`KIcon` is modeled after the icon component of [Pinterest's Gestalt](https://gestalt.netlify.app/#/components/Icon). Something to note is none of their icons use anything other than path. So it is possible to keep what we have implemented and just update the icon library which has been in discussion for a while. If we can unify all of the icons to just use paths this issue is a no-op.

**Comment by kaiarrowood** [comment]
Issue resolved in Kongponents redesign.
