### ISSUE TITLE
KoolTip Component with html

### ISSUE THREAD

**Issue by tharun208** [Kong/kongponents#262]
Currently `KoolTip` doesn't show `HTML` content. Had a use-case in `kuma-gui` where we need to highlight or bold the message of the tooltip.

**Comment by darrenjennings** [comment]
@tharun208 we are reserving kooltip for text only at the moment. Please use KPop if you'd like to have html-styled popover. However, it would be nice to eventually have a second slot for kooltip to be a custom component.

**Comment by tharun208** [comment]
@darrenjennings, let me raise a PR. But, The overall implementation of the `KToolTip` will change if we add a additional slot.
