### ISSUE TITLE
KIcon - color fill - warning

### ISSUE THREAD

**Issue by tomaszwylezek** [Kong/kongponents#338]
Hi!
I tried to upgrade `@kongponents/kicon` from `0.5.0` into some new version but I noticed that starting from `0.5.5` it breaks an icon `warning`

KIcon `0.5.0`
![Screenshot 2021-09-07 at 12 08 38](https://user-images.githubusercontent.com/16152347/132327475-5e21b18a-a2d6-482d-a3c1-ce89fe1c612d.png)

KIcon `0.5.5`
![Screenshot 2021-09-07 at 12 09 05](https://user-images.githubusercontent.com/16152347/132327509-45fc7813-2fd2-4eac-a1e2-6f8ed5f2da92.png)

In both cases, usage is like
```
<KIcon
    color="var(--yellow-400)"
    icon="warning"
/>
```

Expected behavior:
The exclamation mark is still black on the new version.

Please let me know if it's a bug and will be fixed in the new version or I should use SVG from the older version to be able to have noncolored exclamation mark.

**Comment by kaiarrowood** [comment]
Secondary color support added in `KIcon` `v4.0.2`: https://kongponents.netlify.app/components/icon.html#secondarycolor
