### ISSUE TITLE
Support reading $attrs.id in addition to (or instead of) testMode for all components using uuid.v1 for ID generation

### ISSUE THREAD

**Issue by kleinfreund** [Kong/kongponents#756]
## Problem statement

I’m migrating Kuma GUI from kongponents v4 to v6. Among other things, this seems to have introduced the use of vue-uuid’s `uuid.v1` method to generate `id` attribute values. This breaks Kuma GUI’s snapshot test suite because the ID values constantly change.

I’ve found the `testMode` prop on the components for which this happens (e.g. `KCard`); however, I find adding the `testMode` prop to all components in the Kuma GUI code base rather cumbersome. I would need to set it to `true` conditionally (based on the current runtime environment) which is test-specific code I rather not have in non-test code.

(Kuma GUI currently has 35 KCards and 26 KPops (😁) so the effort to change this isn’t terribly big.)

### Read `$attrs.id` in addition to `testMode` to determine ID attribute values (breaking change)

I would like to be able to set ID attributes on these components myself.

Precedent: the KTextArea component (see https://github.com/Kong/kongponents/blob/main/packages/KTextArea/KTextArea.vue#L131) already does this.

1. Use `$attrs.id` if it’s provided
2. Use fixed value if `testMode` is `true`
3. Generate ID using `uuid.v1`

### Read `$attrs.id` instead of `testMode` to determine ID attribute values (breaking change)

Generally, I think reading explicit IDs from the component is strictly better than using the `testMode` prop. It allows control over the value in each unit test rather than relying on _the one_ possible test attribute value.

1. Use `$attrs.id` if it’s provided
2. Generate ID using `uuid.v1`

## Unsuccessful avoidance strategies

<details>
<summary>
Generating snapshots without UUIDs (you don’t want to see this)
</summary>

```js
const template = container.innerHTML // or wrapper.html()
expect(
  template
    .replace(/\bid=".+"/g, 'id="test"')
    .replace(/\baria-describedby=".+"/g, 'aria-describedby="test"')
).toMatchSnapshot()
```

Yeah.

</details>

**Comment by kleinfreund** [comment]
> Are there specific components that are failing, or all of them?

All snapshot tests for components which use a Kongponents component which uses UUIDs fail. In Kuma GUI, that’s all components that use KCard or KPop directly or indirectly.

> If you're providing an id on most components, I believe it should fall through; however, I'm fully aware that this implementation is not supported by all existing components.

Yes, this feature would need to be added to a couple of components. Unfortunately, there isn’t a way to make this a non-breaking change.

> You also may be able to look into using [jest-snapshot-delete-properties](https://www.npmjs.com/package/jest-snapshot-delete-properties)

I’ve had a look at this, but decided to not use it because it doesn’t seem to be maintained actively enough. However, inspired by this, I did look further into the possibility to provide a custom snapshot serializer. It works pretty well, actually. Truth be told, I would rather Kongponents let me provide those attribute values explicitly because this is a lot of extra stuff in the test layer, but on practically-speaking, it isn’t a great approach to have snapshot tests for fully-rendered components. At least the external components should be stubbed so that only what’s controlled by the project is under test.

## A custom snapshot serializer for replacing attribute values that look like UUIDs

**Usage** (e.g. in a Jest setup file):

```typescript
import { replaceAttributesSnapshotSerializer } from './jest-replace-attribute-snapshot-serializer'

expect.addSnapshotSerializer(replaceAttributesSnapshotSerializer([
  'id',
  'aria-describedby',
  'aria-labelledby',
  'aria-controls',
]))
```

**Source** (`jest-replace-attribute-snapshot-serializer.ts`):

```typescript
// Determined by fair dice roll
const DEFAULT_UUID = 'aaaabbbb-cccc-dddd-eeee-ffffffffffff'

function hasUuidAttribute(element: HTMLElement, attribute: string): boolean {
  const value = element.getAttribute(attribute)

  return value !== null && /[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/.test(value)
}

const processedValues = new Set()

export function replaceAttributesSnapshotSerializer(
  attributes: string[],
  uuid = DEFAULT_UUID
): jest.SnapshotSerializerPlugin {
  return {
    test: (value) => value instanceof HTMLElement && !processedValues.has(value)
      ? attributes.some((attribute) => hasUuidAttribute(value, attribute))
      : false,
    serialize: (value, config, indentation, depth, refs, printer) => {
      if (value instanceof HTMLElement) {
        for (const attribute of attributes) {
          if (hasUuidAttribute(value, attribute)) {
            value.setAttribute(attribute, uuid)
          }
        }

        processedValues.add(value)
      }

      return printer(value, config, indentation, depth, refs)
    },
  }
}
```

**Comment by adamdehaven** [comment]
> on practically-speaking, it isn’t a great approach to have snapshot tests for fully-rendered components. At least the external components should be stubbed so that only what’s controlled by the project is under test.

I think this is the root of the issue. 

---

I'm out of the office today through next week, but I can take a better look when I get back. 

We could probably fall through provided ids on most elements; however, this would require us to add `inheritAttrs: false` to every single Kongponent so that we could bind the user-provided ids. 

This won't work in all scenarios though as there are some components that generate ids onto multiple elements within the component.

**Comment by kleinfreund** [comment]
We're using the following custom snapshot serializer (can be used with Jest or Vitest) to replace UUID attributes and remove `data-v-*` attributes so we don't strictly need this anymore.

```ts
// Imports the appropriate plugin type from the library Jest uses for snapshot serialization.
import { Config, NewPlugin, Printer, Refs } from 'pretty-format'

const DEFAULT_UUID = 'aaaabbbb-cccc-dddd-eeee-ffffffffffff'

function hasUuidAttribute(element: Element, attribute: string): boolean {
  const value = element.getAttribute(attribute)

  return value !== null && value !== DEFAULT_UUID && /[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/.test(value)
}

export function replaceAttributesSnapshotSerializer(
  attributes: string[],
  uuid = DEFAULT_UUID,
): NewPlugin {
  return {
    /**
     * Matches elements which haven’t been processed by this serializer before.
     */
    test: (value: any) => {
      if (!(value instanceof Element)) {
        return false
      }

      return (
        attributes.some((attribute) => hasUuidAttribute(value, attribute)) ||
          Object.values(value.attributes).some((attribute) => attribute.name.startsWith('data-v-'))
      )
    },

    /**
     * Replaces the attribute values of an element with a static value.
     */
    serialize: (value: Element, config: Config, indentation: string, depth: number, refs: Refs, printer: Printer) => {
      for (const attribute of attributes) {
        if (hasUuidAttribute(value, attribute)) {
          value.setAttribute(attribute, uuid)
        }
      }

      for (const attribute of value.attributes) {
        if (attribute.name.startsWith('data-v-')) {
          value.removeAttribute(attribute.name)
        }
      }

      return printer(value, config, indentation, depth, refs)
    },
  }
}
```

**Comment by adamdehaven** [comment]
This is great; thanks for sharing here
